### ISSUE TITLE
Waveformplayer.stop() crashes sometimes (v1.2.0-rc1)

### ISSUE THREAD

**Issue by AnwarShahriar** [hushed/WaveFormViewDemo#12]
```
java.lang.IllegalStateException
        at android.media.MediaPlayer._seekTo(Native Method)
        at android.media.MediaPlayer.seekTo(MediaPlayer.java:1821)
        at android.media.MediaPlayer.seekTo(MediaPlayer.java:1833)
        at space.siy.waveformview.FixedWaveFormPlayer.stop(FixedWaveFormPlayer.kt:166)
        at space.siy.waveformview.FixedWaveFormPlayer.stop(FixedWaveFormPlayer.kt:156)
        at com.hushed.base.number.messaging.viewholders.AudioMessageViewHolder.onDetachedFromWindow(AudioMessageViewHolder.kt:135)
        at com.hushed.base.number.messaging.ConversationsMessageAdapter.onViewDetachedFromWindow(ConversationsMessageAdapter.java:257)
        at com.hushed.base.number.messaging.ConversationsMessageAdapter.onViewDetachedFromWindow(ConversationsMessageAdapter.java:30)
        at androidx.recyclerview.widget.RecyclerView.dispatchChildDetached(RecyclerView.java:7404)
        at androidx.recyclerview.widget.RecyclerView$5.removeViewAt(RecyclerView.java:870)
        at androidx.recyclerview.widget.ChildHelper.removeViewAt(ChildHelper.java:168)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.removeViewAt(RecyclerView.java:8501)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.removeAndRecycleViewAt(RecyclerView.java:8774)
        at androidx.recyclerview.widget.LinearLayoutManager.recycleChildren(LinearLayoutManager.java:1374)
        at androidx.recyclerview.widget.LinearLayoutManager.recycleViewsFromEnd(LinearLayoutManager.java:1460)
        at androidx.recyclerview.widget.LinearLayoutManager.recycleByLayoutState(LinearLayoutManager.java:1483)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1509)
        at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1332)
        at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1076)
        at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1839)
        at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:1938)
        at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3292)
        at android.view.View.dispatchTouchEvent(View.java:11776)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2962)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2643)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:448)
```

**Comment by AnwarShahriar** [comment]
This was an issue due to client side implementation, library has nothing to do with it. Though adding a guard for this would be nice, but it would also consume issues which supposed to be handled on client side.
