### ISSUE TITLE
Stopping and dispose call causing IllegalStateException

### ISSUE THREAD

**Issue by AnwarShahriar** [hushed/WaveFormViewDemo#9]
java.lang.IllegalStateException
        at android.media.MediaPlayer.getCurrentPosition(Native Method)
        at space.siy.waveformview.FixedWaveFormPlayer.updatePosition(FixedWaveFormPlayer.kt:37)
        at space.siy.waveformview.FixedWaveFormPlayer.access$updatePosition(FixedWaveFormPlayer.kt:13)
        at space.siy.waveformview.FixedWaveFormPlayer$runnable$1.run(FixedWaveFormPlayer.kt:29)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by AnwarShahriar** [comment]
Fixed in #11
